language: python
python:
  - "3.2"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: apt-get install python-numpy
# command to run tests, e.g. python setup.py test
script: test_all.py
